image: node:12.16.1

stages:
  - test
  - pages
  - build
  - deploy

lint:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn run lint
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/

pages:
  stage: pages
  script:
    - yarn install
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
    expire_in: 1 week
  environment:
    name: 'stage'
    url: https://clearline.gitlab.io/cl-website
  when: manual
  only:
    - merge_requests
  variables:
    GATSBY_ACTIVE_ENV: 'stage'

build_prod:
  stage: build
  allow_failure: false
  before_script:
    - yarn install
  script:
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    when: on_success
    paths:
      - public
    name: 'cl-website-$CI_COMMIT_SHORT_SHA'
    expire_in: 1 week
  variables:
    GA_ID: 'UA-48694500-1'
    GADS_ID: 'AW-983170276'
    FB_PIXEL_ID: '1561387770623152'
  only:
    refs:
      - master
  cache:
    paths:
      - node_modules/

deploy_prod:
  stage: deploy
  allow_failure: false
  dependencies:
    - build_prod
  image: debian:latest
  before_script:
    - apt-get update && apt-get install lftp -y
  script:
    - lftp -e "set ssl:verify-certificate no; set sftp:auto-confirm yes; mirror -eRnv public new; cd new; ls -l; exit;" -u $SFTP_USERNAME,$SFTP_PASSWORD $SFTP_HOST
  environment:
    name: 'prod'
    url: https://clearline.com.ua/new
  when: on_success
  only:
    refs:
      - master
