image: node:12.16.1

stages:
  - test
  - pages

lint:
  stage: test
  before_script:
    - yarn install
  script:
    - yarn run lint
  only:
    - merge_requests

pagesMaster:
  stage: pages
  script:
    - yarn install
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master
  variables:
    CI_ENVIRONMENT_NAME: 'stage'

pages:
  stage: pages
  script:
    - yarn install
    - node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  environment:
    name: 'stage'
    url: https://clearline.gitlab.io/cl-website
  when: on_success
  only:
    - merge_requests
