import { ConversionType } from './conversions'

export type TrackingEventName =
    | 'FormSubminAttempt'
    | 'FormSubminSuccess'
    | 'FormSubminFail'
    | 'Click'
    | 'SocialIcon'
    | 'Phone'
    | 'Email'
    | 'FullScreen'
    | 'ShowSlide'
    | '25'
    | '50'
    | '75'
    | '100'
    | 'Banner'

export type TrackingEventCategory =
    | ConversionType
    | 'DefaultForm'
    | 'LanguageChange'
    | 'ShowMoreButton'
    | 'ShowMoreButtonFAQ'
    | 'Address'
    | 'GoogleRewiews'
    | 'FAQItem'
    | 'ServicesItem'
    | 'WikiItem'
    | 'ReviewItem'
    | 'Slider'
    | 'ScrollDepth'
    | 'Banner'
    | 'ShowExampleOfProject'
    | 'TopFormDesktopPosadka3d'
    | 'TopFormDesktopPosadkaColor'
    | 'TopFormDesktopPosadka99'
    | 'TopFormDesktopPosadka'
    | 'Save Draw'
    | 'FormIndexPageBottom'
    | 'FormServicesPageBottom'
